name: CI/CD Workflow

on:
  push:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}

