jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 其他的步骤...

      - name: SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动生成的令牌，用于授权操作
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # 您在 SonarCloud 注册时获得的令牌
        with:
          projectBaseDir: .   # 项目的根目录
          args: >
            -Dsonar.projectKey=300sky_300sky
            -Dsonar.organization=300sky
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
