name: 自动化 CI/CD 流程

on:
  push:
    branches: [main]

jobs:
  build-and-push-images:
    runs-on: ubuntu-22.04
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 登录 Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin


      - name: 构建并推送应用镜像
        uses: docker/build-push-action@v2
        with:
          context: ./app
          tags: ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: 构建并推送数据库镜像
        uses: docker/build-push-action@v2
        with:
          context: ./db
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mydb:latest
          push: ${{ github.ref == 'refs/heads/main' }}
