name: CI devops 2023
on:
  push:
    branches: [main, develop] # Triggers the workflow on push events to main and develop branches
  pull_request:
    branches: [main, develop] # Optionally, you can also trigger the workflow on pull requests to these branches

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.5.0 # Checks out the current code in the repository

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Specifies JDK 17
          distribution: 'adopt' # Can be 'adopt', 'zulu', etc.

      - name: Build and test with Maven
        run: mvn clean install # Runs the Maven command to build the project and run tests
